---
title: "README"
author: "Xinzhe Dong"
date: "November 13, 2017"
output: github_document
---

*R scripts:*
`00_download-data.R` download the raw data for our example, `gapminder.tsv`.

`01_filter-reorder-plot.R` 
* Bring the data in as data frame. 
* Make some plots, save to file a boxplot of lifeExp and continents, and a scatterplot of lifeExp vs. year. 
* Reorder Gapminder continents by minimum of lifeExp, and write the reordered data to file.

`02_statistical_analysis.R` 
* Fit a linear regression of life expectancy on year within each country. Write the estimated intercepts, slopes, and residual error variance (or sd) to file. 
* Create a scatterplots of life expectancy vs. year for the 4 countries with large sd found in each continent, faceting on countries, fitted line overlaid, and write these plots to file.

`03_gap-report.Rmd` 
* a Rmarkdown document. 
* Its purpose is to allow us to demonstrate how to use `rmarkdown::render()` without the help of RStudio's buttons. We will call `rmarkdown::render()` from within a `Makefile`.

*Master R scripts:*
`Makefile.R` is a master R script that simply `source()`s the three scripts(`00_download-data.R`, `01_filter-reorder-plot.R`, and `02_statistical_analysis.R`), one after the other, with a second “clean up / reset” script that deletes all the output the scripts leave behind.

`render_r_scripts.R` render the `Makefile.R` and emulate RStudio’s “Compile Notebook” button.

*Makefile:*
* a `Makefile` to automate the pipeline using `make`.
* run the R scripts (`00_download-data.R`, `01_filter-reorder-plot.R`, `02_statistical_analysis.R`,`03_gap-report.Rmd`) 
* render an R script, use `Rscript -e "rmarkdown::render('01_filter-reorder-plot.R')"`
* render an RMarkdown report, use `Rscript -e "rmarkdown::render('03_gap-report.Rmd')"`


